version: '3.8'

services:
  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: pos-portal-backend:latest
    container_name: pos-portal-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./backend/.env.production
    networks:
      - pos-portal-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - backend-logs:/app/logs

  # Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: pos-portal-frontend:latest
    container_name: pos-portal-frontend
    ports:
      - "4200:4200"
    networks:
      - pos-portal-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pos-portal-network:
    driver: bridge
    name: pos-portal-network

volumes:
  backend-logs:
    driver: local
