name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  frontend-ci:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: frontend
        
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-${{ github.sha }}
        path: frontend/dist/pos_portal_app/
        retention-days: 7

  frontend-deploy:
    runs-on: self-hosted
    needs: [frontend-ci]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build-${{ github.sha }}
        path: frontend/dist/pos_portal_app/
        
    - name: Create Dockerfile
      run: |
        cat > frontend/Dockerfile << 'EOF'
        FROM nginx:alpine
        COPY dist/pos_portal_app/browser/ /usr/share/nginx/html/
        COPY nginx.conf /etc/nginx/conf.d/default.conf
        EXPOSE 4201
        CMD ["nginx", "-g", "daemon off;"]
        EOF
        
    - name: Temporarily allow dist in Docker context
      run: |
        cd frontend
        # Backup original .dockerignore
        cp .dockerignore .dockerignore.bak
        # Remove dist from .dockerignore for this build
        grep -v "^dist$" .dockerignore > .dockerignore.tmp && mv .dockerignore.tmp .dockerignore
        
    - name: Create nginx config
      run: |
        cat > frontend/nginx.conf << 'EOF'
        server {
            listen 4201;
            server_name localhost;
            root /usr/share/nginx/html;
            index index.html;
            
            location / {
                try_files $uri $uri/ /index.html;
            }
            
            location /api/ {
                proxy_pass http://pos-portal-backend:3000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
        EOF
        
    - name: Create Docker network (if not exists)
      run: |
        docker network create pos-portal-network || true
        
    - name: Build Docker image
      run: |
        cd frontend
        docker build -t pos-portal-frontend:${{ github.sha }} .
        docker tag pos-portal-frontend:${{ github.sha }} pos-portal-frontend:latest
        
    - name: Stop existing container
      run: |
        docker stop pos-portal-frontend || true
        docker rm pos-portal-frontend || true
        
    - name: Deploy new container
      run: |
        docker run -d \
          --name pos-portal-frontend \
          --restart unless-stopped \
          --network pos-portal-network \
          -p 4201:4201 \
          pos-portal-frontend:latest
          
    - name: Verify deployment
      run: |
        sleep 10
        curl -f http://localhost:4201 || exit 1
        echo "Frontend deployed successfully!"
        
    - name: Clean up old images
      run: |
        # Restore original .dockerignore
        cd frontend
        mv .dockerignore.bak .dockerignore
        # Clean up Docker images
        docker image prune -f
        docker images pos-portal-frontend --format "table {{.Repository}}:{{.Tag}}\t{{.CreatedAt}}" | tail -n +2 | head -n -2 | awk '{print $1}' | xargs -r docker rmi || true